config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :bulk_uploads, only: [:index,:create, :new] do
      get :bulk_upload_errors
    end
  end
end

app/models/spree/bulk_upload.rb
require 'csv'
class Spree::BulkUpload < ActiveRecord::Base
  has_attached_file :attachment
  validates_attachment_file_name :attachment, :matches => [/\.(csv)\z/i]
  after_commit :run_import, on: :create

  has_many :bulk_upload_errors, class_name: 'Spree::BulkUploadError'

  def finished?
    total_rows == processed_rows
  end

  def finish_percent
    if total_rows > 0
      (processed_rows / total_rows.to_f) * 100
    else
      100
    end
  end

  def run_import
    uri = if ActionController::Base.asset_host.nil?
      self.attachment.path
    else
      URI.join(ActionController::Base.asset_host,self.attachment.url)
    end
    file = open(uri)
    csv_file = CSV.read(file, {headers: true})
    SpreeBulkUpload::ImportProcessor.new(csv_file, self).run
  end

end

app/models/spree/bulk_upload_error.rb
require 'csv'
class Spree::BulkUploadError < ActiveRecord::Base

  belongs_to :bulk_upload, class_name: 'Spree::BulkUpload'

end

app/controllers/spree/admin/bulk_uploads_controller.rb
module Spree
  module Admin
    class BulkUploadsController < Spree::Admin::BaseController

      respond_to :html

      def index
        @bulk_uploads = Spree::BulkUpload.order(id: :desc).all
        respond_with @bulk_uploads
      end

      def new
        @bulk_upload = Spree::BulkUpload.new
        respond_with(@bulk_upload) do |format|
          format.html { render :layout => !request.xhr? }
          if request.xhr?
            format.js   { render :layout => false }
          end
        end
      end

      def create
        @bulk_upload = Spree::BulkUpload.create(upload_params)
        if @bulk_upload.errors.count>0
          flash[:error] = @bulk_upload.errors.full_messages.join('; ')
        end
        redirect_to admin_bulk_uploads_path
      end

      def bulk_upload_errors
        @bulk_upload_errors = Spree::BulkUpload.find(params[:bulk_upload_id]).bulk_upload_errors
      end

      private

      def upload_params
        params.require(:bulk_upload).permit(:attachment)
      end
    end
  end
end

app/views/spree/admin/bulk_uploads/_table.html.erb
<table class="table" id='listing_prodict_exports'>
  <colgroup>
    <col style="width: 20%">
    <col style="width: 30%">
    <col style="width: 10%">
    <col style="width: 10%">
    <col style="width: 10%">
    <col style="width: 10%">
    <col style="width: 10%">
  </colgroup>
  <thead>
  <tr data-hook="admin_shipping_methods_index_headers">
    <th><%= Spree.t(:attachment_file_name) %></th>
    <th><%= Spree.t(:created_at) %></th>
    <th><%= Spree.t(:total_count) %></th>
    <th><%= Spree.t(:processed_count) %></th>
    <th><%= Spree.t(:progress) %></th>
    <th><%= Spree.t(:bulk_upload_errors) %></th>
    <th data-hook="admin_shipping_methods_index_header_actions" class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% (@bulk_uploads || []).each do |upload|%>
      <%= render partial: 'upload_row', locals: {upload: upload} %>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/bulk_uploads/_upload_row.html.erb
<tr id="<%= spree_dom_id upload %>" data-hook="admin_uploads_index_rows" class="<%= cycle('odd', 'even')%>">
  <td class="align-center"><%= upload.attachment_file_name%></td>
  <td class="align-center"><%= pretty_time(upload.created_at) %></td>
  <td class="align-center"><%= upload.total_rows%></td>
  <td class="align-center"><%= upload.processed_rows %></td>
  <td class="align-center"><%= upload.finish_percent.round(2) %> %</td>
  <td class="align-center"><%= link_to(upload.bulk_upload_errors.count, admin_bulk_upload_bulk_upload_errors_path(upload) ) %> </td>
  <td data-hook="admin_shipping_methods_index_row_actions" class="actions">
  </td>
</tr>

app/views/spree/admin/bulk_uploads/bulk_upload_errors.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:bulk_upload_errors) %>
<% end %>

<% content_for :page_actions do %>
  <span id="back_to_error_list">
    <%= button_link_to Spree.t(:bulk_uploads), admin_bulk_uploads_path, { :class => "btn-success"} %>
  </span>
<% end %>

<table class="table" id='bulk_upload_errors_table'>
  <thead>
  <tr>
    <th><%= Spree.t(:id) %></th>
    <th><%= Spree.t(:error_message) %></th>
    <th><%= Spree.t(:raw_data) %></th>
    <th><%= Spree.t(:created_at) %></th>
  </tr>
  </thead>
  <tbody>

    <% @bulk_upload_errors.each do |e| %>
      <tr>
        <td><%= e.id %></td>
        <td><%= e.error_message %></td>
        <td><%= e.raw_data %></td>
        <td><%= e.created_at %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/spree/admin/bulk_uploads/create.js.erb
$('.no-objects-found').remove();
if ($('#listing_prodict_exports').length == 0) {
    $("#product_exports_wrpper").append('<%= escape_javascript(render partial: 'table') %>');
}
$('#listing_prodict_exports tbody').append('<%= escape_javascript(render partial: 'export_row', locals: {product_export: @product_export}) %>');

app/views/spree/admin/bulk_uploads/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:product_imports) %>
<% end %>

<% content_for :page_actions do %>
  <span id="new_ot_link">
    <%= button_link_to Spree.t(:new_upload), new_admin_bulk_upload_path , { :remote => true, :icon => 'plus', :id => 'admin_new_upload', :class => "btn-success" } %>
  </span>
<% end %>
<div id="new_upload_wrapper">

</div>
<div id="product_imorts_wrpper">
  <% if @bulk_uploads.any? %>
      <%=	render partial: 'table' %>
  <% else %>
      <div class="alpha twelve columns no-objects-found">
        <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/bulk_upload')) %>
      </div>
  <% end %>
</div>

app/views/spree/admin/bulk_uploads/new.html.erb
<%= form_for [:admin, @bulk_upload], method: :post, url: admin_bulk_uploads_path, html: {multipart: true} do |f| %>

  <fieldset data-hook="new_upload">
    <div class="row">
      <legend align="center"><%= Spree.t(:new_upload) %></legend>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :attachment, Spree.t(:attachment) %>
          <%= f.file_field :attachment, :required => true %>
          <%= f.error_message_on :attachment %>
        </div>
      </div>
    </div>
  </fieldset>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.create'), 'ok' %>
  </div>
<% end %>

app/views/spree/admin/bulk_uploads/new.js.erb
$("#new_upload_wrapper").html('<%= escape_javascript(render :template => "spree/admin/bulk_uploads/new", :formats => [:html], :handlers => [:erb]) %>');